### ISSUE TITLE
Missing tokenizer.bin file?

### ISSUE THREAD

**Issue by jdiamondGitHub** [jameswdelancey/llama3.c#12]
I cloned this repository and downloaded the original directory in https://huggingface.co/meta-llama/Meta-Llama-3-8B.  I was able to use export.py to generate 32-bit and 8-bit quantized versions of llama3-8b-instruct.

However, there is no tokenizer.bin file and no ../dev directory, either from hugging face or in this repo.  There is a tokenizer.model from HF, and a tokenizer.py file from this repo, but there are no instructions as to how to convert it to binary form.

Any help would be appreciated.
Thank you for creating this project. :)

**Comment by jdiamondGitHub** [comment]
Update:  I saw that in one of the other branches there was a tokenizer.bin file in the repo, but when I tried it in this branch, it seemed the format was incompatible so I got a failed read error.

**Comment by jdiamondGitHub** [comment]
Update 2:  Tracing the error, it fails with the older tokenizer.bin in reading token 32000,  which sounds like this tokenizer was for the old vocabulary?  I know llama3 now has a huge vocab size.

**Comment by jdiamondGitHub** [comment]
Update 3: I tried using the tokenizer.model file that came from HF, because it seems like the same thing, but again, the format didn't seem to match and it got a failed read error.

**Comment by jdiamondGitHub** [comment]
Update 4:  After googling, I tried this approach to convert the tokenizer.model to a bin format:

not sure if this was needed:
pip3 install sentencepiece

Where I put my model folder
python3 tokenizer.py --tokenizer-model=../llama3-8b-instruct/tokenizer.model

But it fails, getting the error "IndentationError: unexpected indent"

Clearly, some folks have found a tokenizer.bin file that works.  I would be so grateful if someone could add it to the repo.

**Comment by gip** [comment]
The error you are seeing is due to a syntax error in the python script I think: https://github.com/jameswdelancey/llama3.c/blob/master/tokenizer.py#L111 

Takes 10s to fix. CC @jameswdelancey

**Comment by jameswdelancey** [comment]
Thanks for the air cover and @'ing me, @gip.  I haven't any issues with export.py or tokenizer.py; they pass all tests on my end but LMK if you find something.  

Hey @jdiamondGitHub , I added tokenizer.bin for LLaMA3 here. It's a different tokenizer entirely than LLaMA2 (sentencepiece -> tiktoken). Git pull master branch and you'll get the file 4a8d5754d1fc4c4d1650b8b00a8391324bb9cba1

```shell
jd@bob:/d $ git clone https://github.com/jameswdelancey/llama3.c.git
Cloning into 'llama3.c'...
remote: Enumerating objects: 1605, done.
remote: Counting objects: 100% (107/107), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 1605 (delta 57), reused 90 (delta 42), pack-reused 1498
Receiving objects: 100% (1605/1605), 1.28 MiB | 4.36 MiB/s, done.
Resolving deltas: 100% (975/975), done.
jd@bob:/d $ cd llama3.c/
jd@bob:/d/llama3.c (master) $ ls
LICENSE    assets          export.py  requirements.txt  rundll.h  runqdll.c     win.c
README.md  build_msvc.bat  model.py   run.c             runq.c    tokenizer.py  win.h
jd@bob:/d/llama3.c (master) $ gcc -Ofast -march=native -fopenmp run.c win.c -o llama3
jd@bob:/d/llama3.c (master) $ ./llama3.exe
Usage:   run <checkpoint> [options]
Example: run model.bin -n 4096 -i "Once upon a time"
Options:
  -t <float>  temperature in [0,inf], default 1.0
  -p <float>  p value in top-p (nucleus) sampling in [0,1] default 0.9
  -s <int>    random seed, default time(NULL)
  -n <int>    number of steps to run for, default 4096. 0 = max_seq_len
  -i <string> input prompt
  -z <string> optional path to custom tokenizer
  -m <string> mode: generate|chat, default: generate
  -y <string> (optional) system prompt in chat mode
jd@bob:/d/llama3.c (master) $ cp ../tokenizer_llama3.bin tokenizer.bin
jd@bob:/d/llama3.c (master) $ ./llama3.exe ../llama3_8b_instruct_l2c_fmt/llama3_8b_instruct.bin -n 5 -i 'Hello'
Hello, friends! Today
achieved tok/s: 1.718213
jd@bob:/d/llama3.c (master) $ gcc -v
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-14.1.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/include --libexecdir=/mingw64/lib --enable-bootstrap --enable-checking=release --with-arch=nocona --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++,rust,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts --enable-libstdcxx-time --disable-libstdcxx-pch --enable-lto --enable-libgomp --disable-libssp --disable-multilib --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev3, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --disable-libstdcxx-debug --enable-plugin --with-boot-ldflags=-static-libstdc++ --with-stage1-ldflags=-static-libstdc++
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 14.1.0 (Rev3, Built by MSYS2 project)
jd@bob:/d/llama3.c (master) $ ^C
```

**Comment by jameswdelancey** [comment]
> But it fails, getting the error "IndentationError: unexpected indent"

Ah... ok ill check this out but you won't need it now.  Thanks for the head's up @jdiamondGitHub

**Comment by jameswdelancey** [comment]
> The error you are seeing is due to a syntax error in the python script I think: https://github.com/jameswdelancey/llama3.c/blob/master/tokenizer.py#L111
> 


Ah dang, You're right. Fixed in master branch. afa919b Many thanks!!!

**Comment by jdiamondGitHub** [comment]
Thank you so much, James. :)  Amazing response. 👍🏻

**Comment by jdiamondGitHub** [comment]
Thanks to both of you.  I don't actually know any Python, so that's my pain point.  Now I also know the value of the @ . :)

**Comment by jameswdelancey** [comment]
Let me know if you have any more trouble. Here to help.
