### ISSUE TITLE
what is the correct size of exported binary?

### ISSUE THREAD

**Issue by ifbe** [jameswdelancey/llama3.c#13]
hi,
thanks for your great work,

here is my problem:
my pc memory size is 32GB,
when i convert meta-llama model on win11,
all 32GB memory eaten,
and the output file size seem wrong(77aa0401c byte),
is the correct size=35343319068 byte?
(i should add more memory ? )

--------llama2-7b-chat filesize is correct like this--------
converted file size=26954711068(646a0401c)
computed file size=26954711068(646a0401c)

--------llama3-8b-instruct filesize like this--------
converted file size=32122093596(77aa0401c)
computed file size=35343319068(83aa0401c)

console output like this:{
python export.py S:\llama\llama3\Meta-Llama-3-8B-Instruct\llama3_8b_instruct.bin --meta-llama S:\llama\llama3\Meta-Llama-3-8B-Instruct
{'dim': 4096, 'n_layers': 32, 'n_heads': 32, 'n_kv_heads': 8, 'vocab_size': 128256, 'multiple_of': 1024, 'ffn_dim_multiplier': 1.3, 'norm_eps': 1e-05, 'rope_theta': 500000.0}
wrote S:\llama\llama3\Meta-Llama-3-8B-Instruct\llama3_8b_instruct.bin
}

the simple func i use to calc the size: {
	u64 pos = 0x1c;
	pos += 4 * (u64)dim * vocab_size;
	pos += 4 * (u64)dim * n_layers;
	pos += 4 * (u64)dim * dim * n_layers;
	pos += 4 * (u64)dim * dim * n_layers;
	pos += 4 * (u64)dim * dim * n_layers;
	pos += 4 * (u64)dim * dim * n_layers;
	pos += 4 * (u64)dim * n_layers;
	pos += 4 * (u64)hidden_dim * dim * n_layers;
	pos += 4 * (u64)dim * hidden_dim * n_layers;
	pos += 4 * (u64)hidden_dim * dim * n_layers;
	pos += 4 * (u64)dim;
	int head_size = dim / n_heads;
	pos += 4 * (u64)(head_size / 2) * seq_len;
	pos += 4 * (u64)(head_size / 2) * seq_len;
	if(!shared_weights){
		pos += 4 * (u64)dim * vocab_size;
	}
	printf("computed size=%lld(%llx)\n", pos, pos);
}

**Comment by jameswdelancey** [comment]
@ifbe  
1) Thanks for the kind note. You should use the int8 quantized model as you don't have enough ram to do the float32 version. I have a laptop with 32GB and it's in the same ballpark.  The machine I use with the float version of this model has 96GB and the binary uses more than 32GB of ram.

2) On the sizes here's what I have
```
-a----         4/21/2024   6:27 PM    26954711068 llama2_7b.bin
-a----         4/21/2024   7:55 PM     7160348928 llama2_7b_q80.bin
-a----          5/4/2024  10:05 PM     8532934912 llama3_8b_base_q80.bin
-a----         4/29/2024   1:06 AM    32122093596 llama3_8b_base.bin
-a----         4/29/2024  12:31 AM    32122093596 llama3_8b_instruct.bin
-a----          5/3/2024  11:32 AM     8532934912 llama3_8b_instruct_q80.bin
-a----         4/27/2024   7:27 PM        1864861 tokenizer_llama3.bin
-a----         4/28/2024  11:53 PM         433869 tokenizer_llama2.bin
```

**Comment by ifbe** [comment]
ok i will try bigger ram, thank you!
